sudo: required
services:
  -docker

before_install:
  -docker build -t bin130288/dockerdev -f Dockerfile.dev .

Script:
  -docker run -e CI=true bin130288/dockerdev npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "frontend-rj"
  env: "Frontend-rj-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-038462780116 "
  bucket_path: "frontend-rj"
  on:
    branch: main
