name: Docker Image CI

on:
  push:
    branch: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -t bin19095/dockerdev:latest -f Dockerfile.dev .

    - name: Run tests
      run: docker run -e CI=true bin19095/dockerdev npm run test
    
    - name: Deploy to Elastic Beanstalk
      run: |
        zip -r deployment.zip .
        aws s3 cp deployment.zip s3://elasticbeanstalk-ap-southeast-2-038462780116/frontend-rj/
        aws elasticbeanstalk create-application-version \
          --application-name "frontend-rj" \
          --version-label "v-${{ github.run_number }}" \
          --source-bundle S3Bucket=elasticbeanstalk-ap-southeast-2-038462780116,S3Key=frontend-rj/deployment.zip
        aws elasticbeanstalk update-environment \
          --environment-name "Frontend-rj-env" \
          --version-label "v-${{ github.run_number }}"   
