name: Docker Image CI

on:
  push:
    branch: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -t bin19095/dockerdev:latest -f Dockerfile.dev .

    - name: Run tests
      run: docker run -e CI=true bin19095/dockerdev npm run test
    steps:
    - name: Deploy to Elastic Beanstalk
      uses: samuelmeuli/action-elastic-beanstalk@v1
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: ap-southeast-2
        application_name: frontend-rj
        environment_name: Frontend-rj-env
        version_label: v-${{ github.run_number }}
        deployment_package: deployment.zip    
