name: Docker Image CI

on:
  push:
    branch: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -t bin19095/dockerdev:latest -f Dockerfile.dev .

    - name: Run tests
      run: docker run -e CI=true bin19095/dockerdev npm run test
    
    - name: Create deployment package
      run: zip -r deployment.zip .

    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v22
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: 'frontend-rj'
        environment_name: 'Frontend-rj-env'
        version_label: ${{ github.sha }}
        region: ap-southeast-2
        deployment_package: deployment.zip   
