name: Docker Image CI
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t bin19095/dockerdev:latest -f Dockerfile.dev .
      - run: docker run --rm -e CI=true bin19095/dockerdev npm run test
    
      - name: Create deployment package
        run: zip -r deployment.zip . -x '*.git'

      - name: Deploy to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          application_name: docker-gh
          environment_name: Dockergh-env
          existing_bucket_name: elasticbeanstalk-ap-southeast-2-038462780116
          region: ap-southeast-2
          version_label: ${{ github.sha }}
          deployment_package: deployment.zip
        
